---
title: a man with object
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
    sharing: true
    license: false
    aside:
      toc: true
    show_edit_on_github: true
    show_subscribe: true
    pageview: false
text_skin: default
highlight_theme: default
url: https://www.object.run
baseurl: 
description: 'No Description

'
lang: zh
author:
  type: 
  name: wdb
  url: 
  avatar: 
  bio: I am an amazing person.
  email: 
  facebook: 
  twitter: 
  weibo: 
  googleplus: 
  telegram: 
  medium: 
  zhihu: 
  douban: 
  linkedin: 
  github: 
  npm: 
repository: wdbcool/wdbcool.github.io
repository_tree: master
paths:
  root: 
  home: 
  archive: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors: 
mathjax: 
mathjax_autoNumber: 
mermaid: 
chart: 
paginate: 8
paginate_path: "/page:num"
sources: 
sharing:
  provider: false
  addthis:
    id: 
comments:
  provider: gitalk
  disqus:
    shortname: 
  gitalk:
    clientID: 1f52cf41680916c23297
    clientSecret: 2f1252ba94732b044e0d6edc69cd4fdbc2b0068c
    repository: wdbcool.github.io
    owner: wdbcool
    admin: wdbcool
  valine:
    app_id: 
    app_key: 
    placeholder: 
    visitor: 
    meta: 
pageview:
  provider: false
  leancloud:
    app_id: 
    app_key: 
    app_class: 
search:
  provider: default
  google:
    custom_search_engine_id: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
